function logFile = saveOutput(subjectName,runNumber,logFile, cfg, input,varargin)


if nargin > 5
    iseq = varargin{1};
    ipattern = varargin{2};
end

switch input
    
    case 'open'
        
        if ~exist('logfiles','dir')
            mkdir('logfiles')
        end
        
        
        %% .tsv file
        %logfile name for .txt or .tsv
        DateFormat = 'yyyy_mm_dd_HH_MM';
        Filename = fullfile(pwd, 'logfiles', ...
            ['sub-' subjectName, ...
            '_run-' runNumber, ...
            '_' datestr(now, DateFormat) '.txt']);

        
        % open a tsv/txt file to write the output 
        logFile.txt = fopen(Filename, 'w'); %'a'
        fprintf(logFile.txt,'%12s %12s %12s %18s %12s %12s %12s %12s %12s %12s %12s %12s \n', ...
            'SubjID', ...
            'SequenceNum', ...
            'SegmentCateg', ...
            'PatternID', ...
            'PatternOnset', ...
            'PatternEnd', ...
            'PatternDuration', ...
            'TapOnset', ...
            'KeyPresses', ...
            'PatternGridRep',...
            'gridIOI',...
            'F0');
       %  fprintf(fid, 'SubjID\tSequenceNum\tSegmentCateg\tPatternID\tPatternOnset\tTapOnset\tKeyPresses\tPatternGridRep\tgridIOI\tF0\t\n');
        %     logFile.patternOnsets
        %     logFile.patternEnds
        %     logFile.patternDurations
        %     logFile.sequenceOnsets
        %     logFile.sequenceEnds
        %     logFile.sequenceDurations

                % open a tsv/txt file to write the output 
        logFile.responsetxt = fopen(Filename, 'w'); %'a'
        fprintf(logFile.txt,'%12s %12s %12s %18s %12s %12s %12s %12s %12s %12s %12s %12s \n', ...
            'SubjID', ...
            'SequenceNum', ...
            'SegmentCateg', ...
            'PatternID', ...
            'PatternOnset', ...
            'PatternEnd', ...
            'PatternDuration', ...
            'TapOnset', ...
            'KeyPresses', ...
            'PatternGridRep',...
            'gridIOI',...
            'F0');
        

        
    case 'save'


        fprintf(logFile.txt,'%12.0f %12.0f %12s %18s %12.3f %12.3f %12.3f %12.3f %12s %12s %12.3f %12.0f \n', ...
            subjectName, ...
            iseq, ...
            seq.segmCateg, ...
            seq.patternID(ipattern), ...
            logFile.iPatOnset(ipattern,iseq), ...
            logFile.iPatEnd(ipattern,iseq), ...
            logFile.iPatDuration(ipattern,iseq), ...
            seq.outPatterns(ipattern),...
            seq.gridIOI(ipattern,iseq),...
            seq.F0(ipattern,iseq));
        
        
                        
        
    case 'saveresponse'
        
                fprintf(logFile.txt,'%12.0f %12.0f %12s %18s %12.3f %12.3f %12.3f %12.3f %12s %12s %12.3f %12.0f \n', ...
            );
        
        
        responseEvents(iEvent,1).onset = event.Time;
            responseEvents(iEvent,1).trial_type = 'response';
            responseEvents(iEvent,1).duration = 0;
            responseEvents(iEvent,1).key_name = KbName(event.Keycode);
            responseEvents(iEvent,1).pressed =  event.Pressed;
            
            
    case 'savemat'
        
        %.mat file
        save(fullfile('logfiles',[Filename,'_all.mat']))
        
        
    case 'close'
        
        % close txt log file
        fclose(logFile.txt);
        
        
end


end
